apiVersion: v1
kind: Secret
metadata:
      name: cassandra-creds
type: Opaque
data:
  cassandrapassword: Y2Fzc2FuZHJh
  cassandrauser: Y2Fzc2FuZHJh
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  labels:
    app: cassandra
spec:
  ports:
    - port: 9042
      targetPort: 9042
      name: cass
  selector:
    app: cassandra
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: cassandra
spec:
  serviceName: "cassandra"
  replicas: 1
  selector:
    matchLabels:
      app: cassandra
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
        - name: cassandra
          image: cassandra:4.0.6
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 7000
              name: intra-node
            - containerPort: 7001
              name: tls-intra-node
            - containerPort: 7199
              name: jmx
            - containerPort: 9042
              name: cass
          volumeMounts:
            - name: ohs-cass-datadir
              mountPath: /var/lib/cassandra
          env:
            - name: CASSANDRA_CLUSTER_NAME
              value: development-cassandra
            # - name: CASSANDRA_SEEDS
            #   value: "cassandra-0.cassandra"
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
          # resources:
          #   limits:
          #     cpu: "500m"
          #     memory: 1Gi
          #   requests:
          #     cpu: "500m"
          #     memory: 1Gi
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
          lifecycle:
            preStop:
              exec:
                command:
                  - /bin/sh
                  - -c
                  - nodetool drain
          readinessProbe:
            exec:
              command:
                - cqlsh
            initialDelaySeconds: 15
            timeoutSeconds: 5
      terminationGracePeriodSeconds: 60
      volumes:
        - name: ohs-cass-datadir
          persistentVolumeClaim:
            claimName: ohs-cass-datadir
  volumeClaimTemplates:
    - metadata:
        name: ohs-cass-datadir
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 5Gi