name: Server Build and Test

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:
    branches: ["main"]
    paths:
      - "server/**"
      - .github/workflows/build_and_test_server.yml
  pull_request:
    branches: ["main"]
    paths:
      - "server/**"
      - .github/workflows/build_and_test_server.yml

jobs:
  build-and-test-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.20.2'
      - name: Build
        working-directory: ./server
        run: make build
      - name: Test
        working-directory: ./server
        run: make test
        