name: Publish Bleed OpenFoodDiary Container

on:
  push:
    branches: ["main"]

concurrency:
  group: "publish-bleed"
  cancel-in-progress: true

jobs:
  publish-bleed:
    uses: ./.github/workflows/build_docker_image.yml
    with:
      PUSH_VERSION: bleed
      PUSH_LATEST: false
