name: Tilt Run and Test

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *" # run at 2 AM UTC
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test-with-tilt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Kind
        uses: helm/kind-action@v1.4.0
        with:
          install_only: true
      - name: Setup cluster with registry
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/kind-local/master/kind-with-registry.sh | bash
      - name: Install tilt
        run: curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh | bash
      - name: Run Tilt CI w/ cypress
        run: tilt ci -- --run-cypress
      - uses: actions/upload-artifact@v3
        if: always()
        name: Upload test results
        with:
          name: cypress-test-results
          path: |
            test/e2e/cypress/screenshots
            test/e2e/cypress/videos